---
version: "3"
services:
  bun:
    build:
      dockerfile: Dockerfile
      context: ./examples/bun
    ports:
      - 3000:3000
    network_mode: host
    environment:
      - PUBLIC_KEY=${PUBLIC_KEY:-PUB_K1_6Rqd3nkeTzZjXyrM4Nq9HFcagd73vLCEGg6iYGigdTPV7ymQKT}
      - PORT=${PORT:-3000}
  deno:
    build:
      dockerfile: Dockerfile
      context: ./examples/deno
    ports:
      - 3000:3000
    network_mode: host
    environment:
      - PUBLIC_KEY=${PUBLIC_KEY:-PUB_K1_6Rqd3nkeTzZjXyrM4Nq9HFcagd73vLCEGg6iYGigdTPV7ymQKT}
      - PORT=${PORT:-3000}
  express:
    build:
      dockerfile: Dockerfile
      context: ./examples/express
    ports:
      - 3000:3000
    network_mode: host
    environment:
      - PUBLIC_KEY=${PUBLIC_KEY:-PUB_K1_6Rqd3nkeTzZjXyrM4Nq9HFcagd73vLCEGg6iYGigdTPV7ymQKT}
      - PORT=${PORT:-3000}
  node:
    build:
      dockerfile: Dockerfile
      context: ./examples/node:http
    ports:
      - 3000:3000
    network_mode: host
    environment:
      - PUBLIC_KEY=${PUBLIC_KEY:-PUB_K1_6Rqd3nkeTzZjXyrM4Nq9HFcagd73vLCEGg6iYGigdTPV7ymQKT}
      - PORT=${PORT:-3000}
