POST http://localhost:3000 HTTP/1.1
content-type: application/json
x-signature-secp256k1: SIG_K1_K2F8K3JwL9MaVXssP8mK8J9NXxTzaPQGqnjUbN2xSCUaex9km3eFfVYS4c4vcX5axKVG9MvyNjJ736GoruZqtbGHBNzf9A
x-signature-timestamp: 1686579338

{"message":"PING"}